import type { Metadata } from 'next';

import './globals.css';
import Header from '@/components/Header';
import Providers from '@/config/Providers';
import { geistMono, geistSans } from '@/assets/fonts/fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <Providers>
        <body
          className={`${geistSans.variable} ${geistMono.variable} flex h-full w-full flex-col items-center justify-center gap-10 antialiased`}
        >
          <Header />
          {children}
        </body>
      </Providers>
    </html>
  );
}
